ARG GO_VERSION=1.24.2
RUN curl -sSL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz | tar -C /usr/local -xzf - \
    && mkdir -p /home/.go \
    && chown -R $(id -u):$(id -g) /home/.go
ENV PATH="/usr/local/go/bin:/home/.go/bin:${PATH}"
ENV GOPATH="/home/.go"
